/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: 187132f48ddf0f604882ba8213fe386f)
// Runtime types generated with workerd@1.20260317.1 2025-09-27 global_fetch_strictly_public
declare namespace Cloudflare {
  interface Env {
    ASSETS: Fetcher;
  }
}
interface Env extends Cloudflare.Env {}
